# -*- coding: utf-8 -*-
{
    'name': 'Plus-Tech HR Employee Letter',
    'version': '15.0.0.0.0',
    'author': 'Plus Technology Team',
    'company': 'Plus Technology',
    'category': 'Human Resources/Letters',
    'website': "www.plustech-it.com",
    'description': """Manage internal letters""",
    'summary': """Manage internal letters""",
    'depends': ['hr', 'plustech_layout_template'],
    'data': [
        'security/ir.model.access.csv',
        'security/letter_security.xml',
        # 'data/letter_template.xml',
        # 'data/data_salary_definiation_1.xml',
        'data/data_letter_category.xml',
        'data/data_payment_order.xml',
        'data/data_salary_definition.xml',
        'data/data_employee_definition.xml',
        'data/data_salary_definition_02.xml',
        # 'data/transfer_salary_template.xml',
        # 'data/administrative_decision_template.xml',
        # 'data/trial_period_extension_template.xml',
        # 'data/Employee_definition_template.xml',
        # 'data/employee_investigation_template.xml',
        # 'data/employee_internal_clearance.xml',
        # 'data/confidentiality_template.xml',
        # 'data/employee_external_clearance.xml',
        # 'data/experience_certificate _template.xml',
        # 'data/end_of_service_clearance.xml',
        # 'data/custody_request.xml',
        # 'data/car_delivery_template.xml',
        'views/hr_letter.xml',
        'views/letter_template.xml',
        'views/stages.xml',
        'views/letter_categ.xml',
        # 'report/letter_report.xml',
        'report/payment_order_report.xml',
        'report/salary_definition_report.xml',
        'report/employee_definition_report.xml',
        'report/salary_definition_report_2.xml',
    ],
    'assets': {
        'web.report_assets_common': [
            '/plustech_hr_employee_letter/static/description/src/css/style.css',
        ],

    },
    'license': 'LGPL-3',
    'installable': True,
    'auto_install': False,
    'application': False,
}

