# -*- coding: utf-8 -*-
{
    'name': "Plus Tech Hr Business Trip",
    'version': '15.0.0.0.0',
    'author': 'Plus Technology Team',
    'company': 'Plus Technology',
    'category': 'Human Resources/Business Trip',
    'website': "www.plustech-it.com",
    'description': """Manage business of employees""",
    'summary': """Manage business of employees""",
    'depends': ['plustech_hr_employee', 'account', 'base_address_city',
                'plustech_hr_leave', 'plustech_layout_template', 'plustech_hr_flight_ticket'],
    'data': [
        'security/security_view.xml',
        'security/ir.model.access.csv',
        'data/hr_leave_type.xml',
        'data/business_trip_sequence.xml',
        'data/travel_way_data.xml',
        'data/allowance_data.xml',
        'data/cities_data.xml',
        'data/mail_activity.xml',
        'wizard/approval_reject_wizard.xml',
        'wizard/approval_approve_wizard.xml',
        'views/business_trip_view.xml',
        'views/business_trip_allowance.xml',
        'views/payment_view.xml',
        'views/business_trip_ticket.xml',
        'views/travel_way.xml',
        'views/res_country.xml',
        'views/res_config_settings_view.xml',
        'views/res_country_group.xml',
        'views/business_trip_activity.xml',
        'reports/business_trip_request.xml',
    ],
    'license': 'LGPL-3',
}
