# -*- coding: utf-8 -*-

{
    'name': 'PlusTech HR Employee',
    'version': '15.1.1',
    'author': 'Plus Technology Team',
    'company': 'Plus Technology',
    'category': 'Human Resources/Employees',
    'website': "www.plustech-it.com",
    'description': """manage employees data""",
    'summary': """employees module localization""",
    'depends': ['hr', 'resource'],
    'data': [
        'security/ir.model.access.csv',
        'sequence/employee_sequence.xml',
        'views/hr_employee_view.xml',
        'views/hr_notification.xml',
        'views/hr_setting.xml',
        'views/hr_employee_religion.xml',
        'views/ir_sequence.xml',
        'views/job_position_category.xml',
        'data/mail_activity.xml',
        'data/server_action.xml',
        'data/mail_template.xml',
        'data/ir_cron_job.xml',
    ],
    'sequence': 20,
    'demo': [],
    'images': [],
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'LGPL-3',
}
